@ECHO OFF
REM *****************************************************************************************************
REM * Run the Zhao_6A_Run.sql to export create sql
REM * Author: Zhiyue Zhao
REM * Date: March 21, 2016
REM *****************************************************************************************************
REM * Sign on to SQLPlus and invoke the Zhao_6A_Run.sql script
SQLPLUS /nolog @Zhao_6A_Run.sql
EXIT